import { jsPDF } from "jspdf";
import { Payment, Property, User } from "../types";

export const generateInvoicePDF = (payment: Payment, property: Property, tenant: User) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(79, 70, 229); // Indigo 600
  doc.text("TrustRent Receipt", 20, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Receipt ID: #${payment.id.toUpperCase()}`, 20, 30);
  doc.text(`Date: ${payment.date}`, 20, 35);
  
  // Divider
  doc.setDrawColor(200);
  doc.line(20, 45, 190, 45);
  
  // From / To
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("Received From:", 20, 60);
  doc.setFontSize(14);
  doc.text(tenant.name, 20, 68);
  doc.setFontSize(10);
  doc.text(tenant.email, 20, 74);
  
  doc.setFontSize(12);
  doc.text("Property:", 110, 60);
  doc.setFontSize(14);
  doc.text(property.address, 110, 68);
  doc.setFontSize(10);
  doc.text(property.city, 110, 74);
  
  // Payment Details Box
  doc.setFillColor(243, 244, 246); // Gray 100
  doc.rect(20, 90, 170, 50, 'F');
  
  doc.setFontSize(12);
  doc.text("Description", 30, 105);
  doc.text("Amount", 150, 105);
  
  doc.setDrawColor(200);
  doc.line(30, 110, 180, 110);
  
  doc.setFontSize(12);
  doc.text("Monthly Rent Payment", 30, 125);
  doc.text(`$${payment.amount.toFixed(2)}`, 150, 125);
  
  // Total
  doc.setFontSize(16);
  doc.setTextColor(79, 70, 229);
  doc.text(`Total Paid: $${payment.amount.toFixed(2)}`, 110, 160);
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("This receipt was automatically generated by TrustRent.", 20, 280);
  doc.text("Secure Escrow Transaction.", 20, 285);
  
  doc.save(`trustrent_receipt_${payment.date}.pdf`);
};
